locka99/opcua

- types/src/node_id.rs
- types/src/tests/encoding.rs
Currently, NodeIds of the "Numeric" type are encoded as a UInt16
NamespaceIndex and a UInt64 identifier. However, according to the spec
(Table 6 of Part 6), a UInt32 should be used for the identifier.
Fix the en-/decoder accordingly and add a test.
From my understanding of the standard, one could also argue to reduce the integer in the `Identifier` enum to an `UInt32`, but I'm not sure if this is actually correct.
> types: fix encoding of large numeric node ids

- client/src/session.rs
The OPC UA server always revises the session timeout, but previously adjusted it to its configured minimum timeout.
Now the timeout is adjusted to the server's maximum session timeout.
As long as no logic is in place that takes revised_session_timeout into consideration and sends periodic keepalives, this is a simple fix to combat many cases of silently dropped sessions.
> Request the maximum possible session timeout when creating a session.

- core/src/config.rs
`serde::Deserialize` derives from Sized, so there is no need to  mark `Sized` for A
> remove useless Sized

- server/src/services/attribute.rs
- types/src/attribute.rs
- types/src/lib.rs
OPC-UA spec Part 6, table A.1 gives a list of identifiers assigned to
attributes, where five attribute IDs were missing.
These were discovered with UaExpert that appears to explicitly request
some of these.
> types: Add missing AttributeId values

- server/src/comms/tcp_transport.rs
The .NET UA standard client, NetCoreConsoleClient [1] fails to connect
to the sample simple-server, because it decodes a send_buffer_size and
receive_buffer_size that's one higher than it can handle internally.
My working theory is that the client is constrained to buffers of 16
bits, but I'm completely sure of this yet.
Setting the buffer sizes to u16::MAX allows the client to connect and
successfully read the address space of simple-server.
[1] https://github.com/OPCFoundation/UA-.NETStandard/tree/master/SampleApplications/Samples/NetCoreConsoleClient
> server/comms/tcp_transport: Set session settings to u16::MAX

- core/src/supported_message.rs
- tools/schema/gen_supported_message.js
In addition I sorted al the big lists to make it easier to find anything in them. Let me know if you want that part reverted…
The only logical change is on lines 222 and 267.
Fixes #59
> Add ServiceFault to`response_header`

- client/src/session.rs
- if the max session_timeout become std::u64::MAX and the multiplication overflow and panic. A solution is to first divide and then multiply
> - fix for Panic with very large requested_session_timeout, Fixes #62

- client/src/builder.rs
- client/src/client.rs
- client/src/config.rs
- client/src/tests/mod.rs
- crypto/src/certificate_store.rs
- crypto/src/tests/crypto.rs
- samples/client.conf
- samples/server.conf
- server/src/builder.rs
- server/src/config.rs
- server/src/server.rs
- tools/certificate-creator/src/main.rs
We have a setup where we need to use specific client certificates which are fetched from a remote API during startup. These certs are in`PEM` format, so that wasn't possible with the current code. I tried to keep things as inline with the existing code as possible and made sure that the defaults would not change anything.
Additionally I made a small tweak to how certs are written to disk. The (3rd party) OPC server we connect to returns a certificate path which looks like `%BRAND%/UA Server [%UUID%].der`. So in order for this cert to be able to be saved, the directories `trusted/%BRAND%` need to exist. So now when writing a certificate to disk, the path needed is always being created just before writing the cert.
I hope this PR fits your style and vision and that this can be merged. …
> Make it possible to use custom named .pem certs

- client/src/session.rs
Without calling disconnect here, the session can end up in an endless loop. This happens when creating the session succeeded, but the activation failed.
See here some log output that shows an example of this happening: https://gist.github.com/svanharmelen/3f1e52374ccce8bf023dd37bee562a6e
After this explicit `self.disconnect()`, the session is able to recover and reconnect in the next attempt. Not sure if `disconnect()` is the best call for this, but it seems like a good option/solution. If not then please advice what can/should be used instead.
> Make sure to disonnect a failed session

- client/src/builder.rs
- client/src/client.rs
- client/src/config.rs
- crypto/src/certificate_store.rs
- samples/client.conf
This option is sometimes also called `ssl-no-verify` and allows clients to accept certificates that have incorrect values.
We need to connect to a lot of endpoints that we cannot manage ourselves and we get all kinds of errors with the certificates. Fixing those errors is difficult as we do not always have the required access ourselves, yet the endpoints are all 100% trusted. So this options allows us to connect dispite of those errors.
> Add option to skip additional certificate validations

- client/src/builder.rs
- client/src/client.rs
- client/src/comms/tcp_transport.rs
- client/src/config.rs
- client/src/session.rs
- client/src/subscription_timer.rs
- samples/client.conf
- samples/demo-server/src/main.rs
- samples/server.conf
- server/src/builder.rs
- server/src/config.rs
- server/src/http/mod.rs
- server/src/server.rs
The default runtime is a threaded runtime which spawns a background
thread running a reactor instance and then creates a threadpool (with
the number of threads equal the the number of available CPU cores).
Now this creates a lot of threads, especially when multiple runtimes
are started, like in the client package. And while having a lot of
threads should not be a problem, Tokio needs to be able to communicate
between these threads so it (on Linux) creates unix pipes for that.
On an 16 core machine this resulted in around 144 handles per client.
On our system and the way we use multiple clients in our application
this caused us to hit the 1024 default open file handle limit. In most
cases that limit can easily be updated, but in our case that isn't an
option/solution. So I went looking at …
> Use the current thread runtime for Tokio tasks

- client/src/client.rs
- core/src/comms/url.rs
When you use the function `connect_to_endpoint_id` the code uses a function called `find_matching_endpoint` which substitutes the advertised hostname with the one the client supplied.
But when using `connect_to_endpoint` it uses a function called `find_server_endpoint` which does successfully match even if the hostname is different, but in that case it doesn’t substitute the advertised hostname.
This can cause issues when using IP addresses i.c.w. a NAT connection, have a difference in the actual hostname vs the used DNS name or when the server uses a hostname that is not resolvable so you need to connect using an IP address.
It seems this was also an issue with `connect_to_endpoint_id` as there is a mention of this in the code:
```
// Issue #16, #17 - the server may advertise an endpoint …
```
> Always use the supplied hostname when connecting

- core/src/comms/url.rs
Taking a look at the spec, it is talking about URLs, not hostnames. I also had problems connecting to any server using path, while other clients connected successfully, sending the path in the "hello" message.
Also see: https://reference.opcfoundation.org/v104/Core/docs/Part6/7.1.2/#Table51
> [#99] Fix inability to connect to endpoints having a path segment

- client/src/session.rs
This seems to have been lost in the last changes, so adding it back to make `master` work again 😉
> Make sure to register the new subscription

- Cargo.lock
- client/Cargo.toml
- client/src/builder.rs
- client/src/client.rs
- client/src/config.rs
- client/src/session.rs
- client/src/session_retry.rs
- client/src/session_state.rs
- core/src/comms/secure_channel.rs
- core/src/tests/chunk.rs
- samples/client.conf
- server/src/config.rs
- server/src/metrics.rs
- server/src/session.rs
- types/src/data_value.rs
- types/src/date_time.rs
- types/src/encoding.rs
In some situations, were the server setup is managed by a 3rd party, it can be needed to “follow” the server time in the client in order to be able to setup a connection.
This solution is pretty much inline with what is documented [here](https://reference.opcfoundation.org/v104/Core/docs/Part6/6.3/), except in this solution only the time used in the client is adjusted and the host clock is left untouched.
And just to be clear, the offset is only used for the communication and security related parts between the client and the server. For the rest the actuall time will still be used.
I tested this against several 3rd party server and the change resulted in stable connections without any errors, reconnects or constantly renewing security channels.
Fixes #89
> Allow the client to use the server time

- crypto/src/tests/authentication.rs
- crypto/src/user_identity.rs
When calling the ActivateSession Service, the service should accept
UserIdentityToken. For the UserNameIdentityToken, we need to provide a
password and it can be the case that the password needs to be encrypted
even though the SecureChannel's SecurityPolicy is set to None.
This commit adjusts the selection of the EncryptionAlgorithm as outlined
in Table 187 Opc Part 4. In general, we should prefer the
UserTokenIdentity.SecurityPolicy, expect for when it's not specified.
See locka99/opcua#58
> crypto: Properly select encryption algo from security policies

- core/src/comms/message_chunk.rs
- core/src/comms/secure_channel.rs
For the asymmetric padding the server certificate length, is used to send the extra padding byte.
Fixes: #113
I need to run some tests, to ensure all cases are handled correct.
> Async Padding use remote certificate keylength

- types/src/tests/encoding.rs
- types/src/variant.rs
Make it possible to decode a null array. See [Part6 5.2.5](https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.5/)
> decode null array

- client/src/session/session.rs
When using the library - excellent work, btw! :D - I noticed that the sessions would remain open in the OPC UA servers I was connecting to.
Since the current code was already deleting all subscriptions anyway, I decided to also add the [`CloseSession`](https://reference.opcfoundation.org/v104/Core/docs/Part4/5.6.4/) request.
One thing I'm not sure about is how to best test this - if you can give me a hint, I'll gladly do something about that.
> feat: use CloseSession request when disconnecting

- crypto/src/hash.rs
All credit goes to @phlay for pointing this out.
Using regular comparison on the byte slice will abort as soon as the first byte doesn't match. This could open up the system to timing attacks on the verification.
Using `openssl::memcmp::eq`, the comparison runs in constant-time.
> Fix: constant time hash verification

- types/src/diagnostic_info.rs
- types/src/tests/encoding.rs
- types/src/tests/variant.rs
- types/src/variant.rs
Add support for missing Variants for DiagnosticInfo, DataValue and Variant. See issue: #170
> Support missing VariantTypes

- client/src/session/session.rs
I noticed that some operations create a session object that isn't registered with the server but would result in `CloseSession` requests anyway. The best solution would have been to differentiate these two types of session but for now I just added a quick fix to check for the session id in order to determine whether to send `CloseSessionRequest` to the server...
> fix: don't send CloseSession requests for unregistered sessions

- client/src/session/session.rs
- client/src/session/session_state.rs
We encounted a Heuft OPC server that didn’t send a timestamp in the `OpenSecureChannelResponse` message.
Yet it did send the correct timestamp in all other responses, so by adding a few more checks and also updating the offset on session creation fixes the problem.
And at the same time it can help to prevent new clock skew in cases where the channel is kept alive very long and new sessions are created within the existing channel.
> Make the logic to ignore clock skew more robust

- client/src/session/session.rs
- client/src/session/session_state.rs
- client/src/subscription_state.rs
We noticed issues with several different OPC servers were the session was still there, but no data was flowing anymore. After investigating it turned out that the session was properly kept alive, but the subscription weren't. So they were expired and didn't send data anymore, yet nothing was triggered or notified to let the caller know this was happening.
The changes is this PR introduce a keep alive mechanism for subscriptions and adds the states `BadNoSubscriptions` and `BadSubscriptionIdInvalid` as fatal states that cause the session to close so it can be restarted again...
Text from the web that describes the used fields: 
```
The client’s responsibility is to send PublishRequests to the server, in order to enable
the server to send PublishResponses back. The PublishResponses are used …
```
> Make sure subscriptions are kept alive

- lib/src/types/variant.rs
When array_length is decoded and greater than zero, the configured
decoding options are checked, casting max_array_length to i32. The type
is a usize. We set max_array_length = usize::MAX, resulting the cast to
produce -1 (as an i32) and returning BadEncodingLimitsExceeded.
Given that array_length is cast to a usize immediately after this check,
it makes sense to first convert to it to usize and perform the
comparison on usize instead of i32.
> types/variant: fix cast to i32 that might result in negative number

- lib/src/client/comms/tcp_transport.rs
- lib/src/client/message_queue.rs
- lib/src/client/session/session.rs
- lib/src/client/session/session_state.rs
- lib/src/core/comms/message_writer.rs
- lib/src/core/comms/tcp_codec.rs
- lib/src/server/comms/tcp_transport.rs
This revamps the connection handling on both the client and the server
to guarantee that we never have rogue tokio tasks running.
This simplifies the connection management code by using native rust and tokio
future cancelling to make sure all concurrent code stops when a connection dies,
whatever the reason.
This allows removing a lot of complex connection state management code.
In the new design, if either the read or the write loop needs to terminate the connection, it can do so by simply returning from the current function.
Fixes #199
Fixes #179
This is a base for future pull requests, that I am afraid to do with the current complex state management code.
> Fix memory leaks in connection management code

- lib/src/core/comms/secure_channel.rs
SecureChannel.token_created_at was set using the OPC server time which could cause connection failures if the OPC server is not configured correctly.
Changed so that the same time source is used to determine the token lifetime (DateTime::now())
Fixes #206
> Use DateTime for token creation time

- lib/src/server/comms/tcp_transport.rs
Currently, `server/services/session.rs:activate_session`, locks `session`, then later in `server/events/audit/mod.rs:AuditLog::raise_and_log`, locks `address_space`. Meanwhile `spawn_subscription_task` locks `address_space` then `session`. This reorders the `spawn_subscription_task` lock ordering to match.
> fix out of order address_space/session locking causing deadlock

- lib/src/server/address_space/address_space.rs
This updates the cast of MaxBrowseContinuationPoints to match the UInt16 datatype as specified in the schema.
> Set MaxBrowsePoints datatype as u16

- lib/src/server/services/session.rs
fix out of order locking between server_state and session_manager causing deadlock.
Deadlock occurred in the following scenario:
```
thread 1:
spawn_reading_loop_task:
tcp_transport.rs:423:		transport.write_lock
handle_message():
message_handler.rs:124		session_manager.write_lock
create_session()
session.rs:45			server_state.write_lock
thread 2:
spawn_reading_loop_task
tcp_transport.rs:423		transport.write_lock
close_session:
session.rs:337			server_state.write_lock
session.rs:345			session_manager.read_lock
```
> fix out of order locking between server_state and session_manager 

- tools/schema/gen_datatypes.js
- tools/schema/types.js
Uses the nodeset `<Definition>` to generate types and enums
Also generates Unions, which have it's binary codec defined here:
https://reference.opcfoundation.org/v104/Core/docs/Part6/5.2.8/ 
Probably the CLI args of types.js could be better.
Would like to know how you think it should be done
Add another arg for a nodeset file, rename the bsd arg,
or create another .js file? Then i'll properly edit the README.md
Also, looks like you already thought about `<Definition>` here:
https://github.com/locka99/opcua/blob/b7e7573a48771a55a79819c3e15e66267e8b7ab3/tools/schema/nodeset.js#L375
Would you like that the xml decoding code to be there?
Thanks!
> generate types and enums from nodeset

- lib/src/types/guid.rs
- lib/src/types/variant.rs
Good day,
great library, thanks! for my project it was missing casting from Variant to Rust primitives and arrays of primitives, submitting an implementation. I also extended casting from Variant:Boolean with casting to numeric ones.
> impl from Variant for primitives and prim. arrays, bool casting extended

- Cargo.lock
- lib/src/core/fuzz/Cargo.lock
Improves on #274 by updating the core/fuzz binary as well.
> Update openssl 0.10.41 -> 0.10.55

- lib/src/core/fuzz/Cargo.lock
- lib/src/core/fuzz/Cargo.toml
- lib/src/core/fuzz/fuzz_targets/fuzz_comms.rs
- lib/src/types/fuzz/Cargo.lock
- lib/src/types/fuzz/Cargo.toml
- lib/src/types/fuzz/fuzz_targets/fuzz_deserialize.rs
Updates Cargo.toml files for the fuzz binaries, fixes up the fuzzer runners, and update Cargo.lock.
> {core,types}/fuzz: update dependencies

- docs/client.md
- lib/src/server/builder.rs
Looks like ServerBuilder is based on ClientBuilder an there have been some copypasta left behind.
Make those "client" -> "server" changes in the comments.
Client.md says setting reconnection attempts to zero would make the client reconnect continuously forever, but really the value needs to be -1. Zero would set the client to never try to reconnect.
Just testing the waters with a small PR.
> Fix minor errors in documentation

- integration/src/harness.rs
I missed this in my original client implementation. Using `spawn_blocking` means that tests tend to not terminate if something goes wrong, but the server _is_ async, so that is just completely unnecessary. This neatly handles panics in tasks and properly finishes the test if something goes wrong.
> Run server on a regular tokio task in tests

- lib/src/core/comms/secure_channel.rs
- lib/src/types/date_time.rs
- samples/demo-server/src/machine.rs
with TimeDelta::try_*.unwrap().
Both solutions panic when fed invalid input.
> refactor: Replace deprecated chrono::Duration::*

- .github/workflows/main.yml
> in order to get rid of the node.js 16 warning
Eventually this might be better handled by dependabot instead of manual bumps.
> build: Update action/checkout from v3 to v4

- lib/src/client/transport/core.rs
- samples/demo-server/src/methods.rs
- samples/demo-server/src/scalar.rs
- samples/web-client/src/main.rs
> on vectors for better readability and idiomacy.
> refactor: Prefer first() over get(0)

- .github/workflows/ci_verify_clean_status_codes.yml
- .github/workflows/main.yml
- rustfmt.toml
> in order to enforce congruence between it and its source csv.
> 
> Furthermore drop the generated file from rustfmt ignore as it's apparently currently formatted.
> ci: Regenerate and verify the status codes file

- .github/workflows/ci_verify_clean_supported_message.yml
- .github/workflows/main.yml
- rustfmt.toml
- tools/schema/gen_supported_message.js
> in order to enforce congruence between it and its source list.
> 
> Furthermore drop the generated file from rustfmt ignore
> as it's apparently currently formatted.
> ci: Regenerate and verify the supported messages file

- .github/workflows/main.yml
> as this might help detecting upcoming rust issues earlier next time.
> 
> (cherry picked from commit 1c0bc5cbd65dcd0dcca61e6d0000bbb9c3200cc5)
~This is just a verification of @vlnzrv's finding which gets resolved in #361.~
~This is not meant to be merged by its own.~
Now that #361 has been superseeded by a52f8f739f5c, the CI addition is the only interesting thing left in this PR:
> ci: Run builds across the beta channel as well

- .github/workflows/ci_verify_clean_address_space.yml
- .github/workflows/main.yml
- rustfmt.toml
> in order to enforce congruence between it and the source nodeset.
> 
> Furthermore drop the generated file from rustfmt ignore
> as it's apparently currently formatted.
> ci: Regenerate and verify the address space files

- .github/workflows/ci_verify_clean_types.yml
- .github/workflows/main.yml
- rustfmt.toml
- tools/schema/types.js
> in order to enforce congruence between them and the schema.
> 
> Furthermore drop the generated files from rustfmt ignore
> as they're apparently currently formatted.
Also this resolves #349.
> ci: Regenerate and verify the types files

- .github/workflows/ci_verify_clean_node_ids.yml
- .github/workflows/main.yml
- rustfmt.toml
> in order to enforce congruence between it and the source file.
> 
> Furthermore drop the generated file from rustfmt ignore as it's apparently currently formatted.
> ci: Regenerate and verify the node ids file

- lib/src/server/session.rs
- lib/src/server/session_diagnostics.rs
- lib/src/types/service_types/impls.rs
- lib/src/types/service_types/server_diagnostics_summary_data_type.rs
- lib/src/types/service_types/service_counter_data_type.rs
- lib/src/types/variant.rs
- tools/schema/types.js
> in favor of the corresponding macro.
> refactor: Drop manual default implementations

- samples/demo-server/src/machine.rs
- samples/demo-server/src/main.rs
> such as `use somecrate` is unnecessary in rust.
> refactor: Drop imports of components only used once

- lib/src/client/session/connect.rs
> as it only extends lifetimes at this point and is likely a refactoring artifact.
If this does not break everything, this closes #370.
Thanks @einarmo for the fast explanation in the issue!
> feat: Drop expendable drop
